"""Build the blog from approved structured text, using only Python's stdlib."""
import json
import re
from datetime import date
from html import escape
from pathlib import Path
from string import Template

ROOT = Path(__file__).resolve().parent.parent
BASE = Template((ROOT / 'blog/base.html').read_text())


def e(value):
    return escape(str(value), quote=True)


def validate(posts):
    slugs = set()
    for post in posts:
        slug = post['slug']
        if not re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', slug) or slug in slugs:
            raise ValueError('Article slugs must be unique lowercase URL segments')
        slugs.add(slug)
        if post['status'] not in ('draft', 'published'):
            raise ValueError('Use draft or published status')
        if 'featured' in post and not isinstance(post['featured'], bool):
            raise ValueError('featured must be boolean')
        date.fromisoformat(post['date'])
        for key in ('title', 'description'):
            if not isinstance(post[key], str) or not post[key].strip():
                raise ValueError(f'Missing {key}')
        if not post['blocks']:
            raise ValueError('Article body is empty')
        for block in post['blocks']:
            if block['type'] in ('paragraph', 'heading'):
                if not isinstance(block['text'], str) or not block['text'].strip():
                    raise ValueError('Empty text block')
            elif block['type'] == 'list':
                if not block['items'] or not all(isinstance(item, str) and item.strip() for item in block['items']):
                    raise ValueError('Empty list')
            else:
                raise ValueError('Unknown content block')


def shell(content, title, description, current='false'):
    return BASE.substitute(content=content, title=e(title), description=e(description), blog_current=current)


def date_label(value):
    return date.fromisoformat(value).strftime('%d.%m.%Y')


def render(posts, output):
    validate(posts)  # Validate everything before modifying generated files.
    published = sorted((p for p in posts if p['status'] == 'published'), key=lambda p: (p['date'], p['slug']), reverse=True)
    intro = '<section class="wrap blog-intro"><p class="eyebrow">NEEDLE SHARK / БЛОГ</p><h1>Блог<span class="title-dot">.</span></h1><p>О материалах, изделиях и работе производства.</p></section>'
    cards = ''.join(f'<article class="blog-card"><time datetime="{e(p["date"])}">{date_label(p["date"])}</time><div><h2><a href="/blog/{p["slug"]}/">{e(p["title"])} <span aria-hidden="true">↗</span></a></h2><p>{e(p["description"])}</p></div></article>' for p in published)
    collection = f'<section class="wrap blog-list" aria-label="Статьи">{cards}</section>' if cards else '<section class="wrap blog-empty" aria-labelledby="empty-title"><h2 id="empty-title">Здесь появятся<br>первые статьи.</h2><div><p>Публикаций пока нет. А познакомиться с нашими изделиями можно уже сейчас.</p><a href="/catalog/">Перейти в каталог <span aria-hidden="true">↗</span></a></div></section>'
    pages = {'index.html': shell(intro + collection, 'Блог — Needle Shark', 'Блог Needle Shark: материалы, изделия и работа производства.', 'page')}
    for post in published:
        blocks = []
        for block in post['blocks']:
            if block['type'] == 'list':
                blocks.append('<ul>' + ''.join(f'<li>{e(item)}</li>' for item in block['items']) + '</ul>')
            else:
                tag = 'h2' if block['type'] == 'heading' else 'p'
                blocks.append(f'<{tag}>{e(block["text"])}</{tag}>')
        body = f'<article class="wrap blog-article"><a class="blog-back" href="/blog/">← Все статьи</a><h1>{e(post["title"])}</h1><time datetime="{e(post["date"])}">{date_label(post["date"])}</time><p class="article-lead">{e(post["description"])}</p>{"".join(blocks)}<a class="blog-back" href="/blog/">← Вернуться в блог</a></article>'
        pages[f'{post["slug"]}/index.html'] = shell(body, post['title'] + ' — Needle Shark', post['description'])
    output.mkdir(parents=True, exist_ok=True)
    # Remove only obsolete HTML carrying this generator's ownership marker.
    marker = '<!-- Generated by blog/render.py -->'
    for old in output.glob('*/index.html'):
        if old.relative_to(output).as_posix() not in pages and old.read_text().startswith(marker):
            old.unlink()
    for name, html in pages.items():
        path = output / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(marker + '\n' + html)


def render_featured(posts, homepage):
    validate(posts)
    selected = sorted((p for p in posts if p['status'] == 'published' and p.get('featured', False)), key=lambda p: (p['date'], p['slug']), reverse=True)[:3]
    content = '<div class="popular-grid">' + ''.join(f'<article><h3><a href="/blog/{p["slug"]}/">{e(p["title"])}</a></h3><p>{e(p["description"])}</p></article>' for p in selected) + '</div>' if selected else '<p>Здесь появится подборка материалов из нашего блога.</p>'
    block = '<!-- BLOG_FEATURED_START -->\n<section class="wrap popular-articles" aria-labelledby="popular-heading"><div><h2 id="popular-heading">Популярные статьи</h2><a href="/blog/">Весь блог ↗</a></div>' + content + '</section>\n<!-- BLOG_FEATURED_END -->'
    source = homepage.read_text()
    pattern = r'<!-- BLOG_FEATURED_START -->.*?<!-- BLOG_FEATURED_END -->'
    if len(re.findall(pattern, source, flags=re.S)) != 1:
        raise ValueError('Expected one featured block in homepage')
    homepage.write_text(re.sub(pattern, lambda _: block, source, flags=re.S))


if __name__ == '__main__':
    posts = json.loads((ROOT / 'blog/posts.json').read_text())
    render(posts, ROOT / 'dist/blog')
    render_featured(posts, ROOT / 'dist/index.html')
