BEGIN;
SET LOCAL lock_timeout = '5s';
ALTER TABLE orders
 ADD COLUMN IF NOT EXISTS product_slug TEXT,
 ADD COLUMN IF NOT EXISTS product_name TEXT,
 ADD COLUMN IF NOT EXISTS product_size TEXT,
 ADD COLUMN IF NOT EXISTS inquiry_type TEXT,
 ADD COLUMN IF NOT EXISTS quantity INTEGER CHECK (quantity BETWEEN 1 AND 1000000),
 ADD COLUMN IF NOT EXISTS source_path TEXT;
COMMIT;
